- name: HostName Configuring
  ansible.builtin.shell: set-hostname {{ comp }}-{{ env }}

- name: Installing "{{ package }}"
  ansible.builtin.package:
    name: "{{ package }}"
    state: present

- name: App user
  ansible.builtin.user:
    name: "{{ appuser }}"
    state: present
    create_home: yes

- name: Remove folder for new "{{ appdir }}"
  ansible.builtin.file:
    path: "{{ appdir }}"
    state: absent 

- name: New folder for "{{ package }}"
  ansible.builtin.file:
    path: "{{ appdir }}"
    state: directory    

- name: Download and Extract {{ comp }}
  ansible.builtin.unarchive: 
    src: "{{ url }}"
    dest: "{{ appdir }}"
    remote_src: yes

- name: Genrating arttifacts of mv packages
  ansible.bulitin.command:
    cmd: mvn clean package && mv target/shipping-1.0.jar shipping.jar
    chdir : "{{ appdir }}"
  
- name: Updating {{ comp }} conf 
  ansible.builtin.template:
    src: "{{ comp }}.service"
    dest: /etc/systemd/system/{{ comp }}.service 

- name: Installing mysql for schema
  ansible.builtin.package:
    name: mysql
    state: present

- name: Injecting schema
  loop: "{{ schema }}"
  ansible.builtin.shell: mysql -h mysql-{{ env }}.robobuy.site -uroot -pRoboShop@1 < /app/db/{{ item }}

- name: Starting services
  ansible.builtin.service:
    name: "{{ comp }}"
    enabled: yes
    state: restarted
    daemon_reload: yes