- name: HostName Configuring
  ansible.builtin.shell: set-hostname {{ comp }}-{{ env }}

- name: Installing needed"{{ package }}s"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ package }}"

- name: App user
  ansible.builtin.user:
    name: "{{ appuser }}"
    state: present
    create_home: yes

- name: Remove folder for new "{{ appdir }}"
  ansible.builtin.file:
    path: "{{ appdir }}"
    state: absent 

- name: New folder for "{{ package }}"
  ansible.builtin.file:
    path: "{{ appdir }}"
    state: directory    

- name: Download and Extract {{ comp }}
  ansible.builtin.unarchive: 
    src: "{{ url }}"
    dest: " {{ appdir }}"
    remote_src: yes

- name: Genrating arttifacts of packages
  ansible.builtin.pip:
    requirements: "{{appdir}}/requirements.txt"
    executable: pip3

- name: Updating {{ comp }} conf 
  ansible.builtin.template:
    src: "{{ comp }}.service"
    dest: /etc/systemd/system/{{ comp }}.service  

- name: Starting services
  ansible.builtin.service:
    name: "{{ comp }}"
    enabled: yes
    state: restarted
    daemon_reload: yes