- name: HostName Configuring
  ansible.builtin.shell: set-hostname {{ comp }}-{{ env }}

- name: Disabling default "{{ package }}" vesrion
  ansible.builtin.shell: dnf module disable "{{ package }}" -y

- name: Enabling default "{{ package }}" vesrion
  ansible.builtin.shell: dnf module enable "{{ package }}":"{{ version }}" -y 

- name: Installing "{{ package }}"
  ansible.builtin.package:
    name: "{{ package }}"
    state: present

- name: App user
  ansible.builtin.user:
    name: "{{ appuser }}"
    state: present
    create_home: yes

- name: Remove folder for new "{{ appdir }}"
  ansible.builtin.file:
    path: "{{ appdir }}"
    state: absent 

- name: New folder for "{{ package }}"
  ansible.builtin.file:
    path: "{{ appdir }}"
    state: directory    

- name: Download and Extract {{ comp }}
  ansible.builtin.unarchive: 
    src: "{{ url }}"
    dest: "{{ appdir }}"
    remote_src: yes

- name: Genrating arttifacts of packages
  community.general.npm:
    path: "{{ appdir }}"

- name: Updating {{ comp }} conf 
  ansible.builtin.template:
    src: "{{ comp }}.service"
    dest: /etc/systemd/system/{{ comp }}.service 

- name: Config the mongod repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing mongodbShell
  ansible.builtin.package:
    name: mongodb-mongosh
    state: present

- name: Injecting Mongodb schema 
  ansible.builtin.shell: "mongosh --host mongodb-{{ env }}.robobuy.site < /app/db/master-data.js"

- name: Starting services
  ansible.builtin.service:
    name: "{{ comp }}"
    enabled: yes
    state: restarted
    daemon_reload: yes