url: "https://stan-robotshop.s3.amazonaws.com/cart-v3.zip"
package: "nodejs"
version: "20"
comp: "cart"
appuser: "roboshop"
appdir: "/app"

secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/{{ comp  }}-{{ env }} token={{ token }} url=http://vault-tool.robobuy.site:8200 validate_certs=false') }}"