- name: Creating of user and App
  ansible.builtin.include_role:
    name: common
    tasks_from: hostname

- name: Installing "{{ package }}"
  ansible.builtin.package:
    name: "{{ package }}"
    state: present

- name: Creating of user and App
  ansible.builtin.include_role:
    name: common
    tasks_from: appusercreate

- name: Genrating arttifacts of mv packages
  ansible.builtin.shell:
    cmd: mvn clean package && mv target/shipping-1.0.jar shipping.jar
    chdir : "{{ appdir }}"
  
- name: Updating {{ comp }} conf 
  ansible.builtin.template:
    src: "{{ comp }}.service"
    dest: /etc/systemd/system/{{ comp }}.service 



- name: Starting services
  ansible.builtin.service:
    name: "{{ comp }}"
    enabled: yes
    state: restarted
    daemon_reload: yes