- name: Config of HostName
  anisble.builtin.include_role:
    name: common
    task_from: hostname

- name: Disabling default "{{ package }}" vesrion
  ansible.builtin.shell: dnf module disable "{{ package }}" -y

- name: Enabling default "{{ package }}" vesrion
  ansible.builtin.shell: dnf module enable "{{ package }}":"{{ version }}" -y 

- name: Installing "{{ package }}"
  ansible.builtin.package:
    name: "{{ package }}"
    state: present

- name: Creating of user and App
  anisble.builtin.include_role:
    name: common
    task_from: appusercreate

- name: Genrating arttifacts of packages
  community.general.npm:
    path: "{{ appdir }}"

- name: Config of HostName
  anisble.builtin.include_role:
    name: common
    task_from: injectMongoschema

- name: Config of HostName
  anisble.builtin.include_role:
    name: common
    task_from: configservice