- name: Configuring the HostName
  ansible.builtin.shell: set-hostname {{ comp }}-{{ env }}

- name: Configuring the "{{ package }}" repo
  ansible.builtin.template:
    src: "{{ package }}.repo"
    dest: "/etc/yum.repos.d/{{ package }}.repo"

- name: Installing "{{ package }}" services
  ansible.builtin.package:
    name: "{{ package }}"
    state: present

- name: Installing yum-utils
  ansible.builtin.package:
    name: yum-utils
    state: present

- name: Replace of IP changes to "{{ package }}" services
  ansible.builtin.replace:
    path: "/etc/{{ comp }}/{{ comp }}.conf"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Replace of IP changes to "{{ package }}" services
  ansible.builtin.replace:
    path: "/etc/{{ comp }}/{{ comp }}.conf"
    regexp: 'protected-mode yes'
    replace: 'protected-mode no'

- name: Starting services
  ansible.builtin.service:
    name: "{{ package }}"
    enabled: yes
    state: restarted

