- name: Disabling default Nginx vesrion
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enabling default Nginx vesrion
  ansible.builtin.shell: dnf module enable nginx:1.24 -y 

- name: Installing Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Starting services
  ansible.builtin.service:
    name: nginx
    enable: yes
    state: Started