- name: HostName Configuring
  ansible.builtin.shell: set-hostname frontend-{{ env }}

- name: Disabling default "{{ package }}" vesrion
  ansible.builtin.shell: dnf module disable "{{ package }}" -y

- name: Enabling default "{{ package }}" vesrion
  ansible.builtin.shell: dnf module enable "{{ package }}":"{{ version }}" -y 

- name: Installing "{{ package }}"
  ansible.builtin.package:
    name: "{{ package }}"
    state: present
    

- name: Clean of the default "{{ package }}"
  ansible.builtin.file:
    path: "/usr/share/{{ package }}/html"
    state: absent

- name: New folder for "{{ package }}"
  ansible.builtin.file:
    path: "/usr/share/{{ package }}/html"
    state: directory    

- name: Download and Extract frontend
  ansible.builtin.unarchive: 
    src: "{{ url }}"
    dest: "/usr/share/{{ package }}/html"
    remote_src: yes

- name: Updating Nginx conf 
  ansible.builtin.template:
    src: nginx.conf"
    dest: /etc/nginx/nginx.conf  

- name: Starting services
  ansible.builtin.service:
    name: "{{ package }}"
    enabled: yes
    state: restarted