- name: HostName Configuring
  ansible.builtin.shell: set-hostname frontend-{{ env }}

- name: Disabling default Nginx vesrion
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enabling default Nginx vesrion
  ansible.builtin.shell: dnf module enable nginx:1.24 -y 

- name: Installing Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Download and Extract frontend
  ansible.builtin.unarchive: 
    src: "{{ url }}"
    dest: /tmp/
    remote_src: yes

- name: Clean of the default Nginx
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent    

- name: Starting services
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started