- name: Config the mongod repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing mongodbShell
  ansible.builtin.package:
    name: mongodb-mongosh
    state: present

- name: Injecting Mongodb schema 
  ansible.builtin.shell: "mongosh --host mongodb-{{ env }}.robobuy.site < /app/db/master-data.js"
